language: node_js

addons:
  apt:
    packages:
      - libgconf-2-4
      
deploy:
  provider: script
  script:
    - yarn install && yarn lint && yarn checkout && yarn ci
  skip_cleanup: true
  on:
    branch: master

cache:
  npm: true
  directories:
    - ~/.cache
    - ./public
