language: node_js

addons:
  apt:
    packages:
      - libgconf-2-4
      
deploy:
  provider: script
  script:
    - yarn install && yarn lint && yarn checkout && yarn blog:ci
  skip_cleanup: true

cache:
  npm: true
  directories:
    - ~/.cache
    - ./blog
